{% set name = "astropy-iers-data" %}
{% set version = "0.2025.3.3.0.34.45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 22ce2349ee288b09cb4cc13a6e015a3c8d4ace66ed2eae49b42119d943f6d5e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - astropy_iers_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropy/astropy-iers-data/
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
