{% set name = "astropy-iers-data" %}
{% set version = "0.2025.2.10.0.33.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 03d93817588ef2344e22d56f7a11cba2ecd877ddb2d0fc259a1daf3980c33c3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - astropy_iers_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropy/astropy-iers-data/
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
