{% set name = "astropy-iers-data" %}
{% set version = "0.2025.10.20.0.39.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ba292db8d5cff8d7a1b16793dc23c2016d7f6c4355c8002925e454d9af2c1938

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - astropy_iers_data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astropy/astropy-iers-data/
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - astrofrog
    - mwcraig
